Document: mosburn-destkop
Title: Debian mosburn-destkop Manual
Author: <insert document author here>
Abstract: This manual describes what mosburn-destkop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mosburn-destkop/mosburn-destkop.sgml.gz

Format: postscript
Files: /usr/share/doc/mosburn-destkop/mosburn-destkop.ps.gz

Format: text
Files: /usr/share/doc/mosburn-destkop/mosburn-destkop.text.gz

Format: HTML
Index: /usr/share/doc/mosburn-destkop/html/index.html
Files: /usr/share/doc/mosburn-destkop/html/*.html
